name: Build and Deploy ASP.NET Core App to Azure Web App

env:
  AZURE_WEBAPP_NAME: MyMvcApp-Fer    # Nombre de tu Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'    # Ruta del proyecto web (por defecto, la raíz del repositorio)
  DOTNET_VERSION: '8.0'             # Versión de .NET a usar

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout Code
        uses: actions/checkout@v4

      # Configurar .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Cachear dependencias de NuGet
      - name: Cache NuGet Packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Construir la aplicación
      - name: Build with .NET
        run: dotnet build --configuration Release

      # Publicar la aplicación
      - name: Publish Application
        run: dotnet publish -c Release -o ${{ github.workspace }}/published-app

      # Subir artefactos para el trabajo de despliegue
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ${{ github.workspace }}/published-app

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      # Descargar artefactos del trabajo de construcción
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: published-app

      # Desplegar en Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/published-app